services:
  - type: web
    name: lenslink-api
    env: docker
    dockerContext: lenslink-api
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - fromDatabase:
          name: lenslink-db
          property: host
        key: DB_HOST
      - fromDatabase:
          name: lenslink-db
          property: port
        key: DB_PORT
      - fromDatabase:
          name: lenslink-db
          property: database
        key: DB_DATABASE
      - fromDatabase:
          name: lenslink-db
          property: user
        key: DB_USERNAME
      - fromDatabase:
          name: lenslink-db
          property: password
        key: DB_PASSWORD

databases:
  - name: lenslink-db
    plan: free
    region: singapore
